### ISSUE TITLE
Getting error in calling ratelimited route if set RATELIMIT_ENABLED=False in config 

### ISSUE THREAD

**Issue by kodekracker** [laurentS/slowapi#35]
We were trying to disable ratelimit check for all routes which are marked/decorated with `limiter.limit()`. For that, we set `RATELIMITE_ENABLED=False` in `.env` file or set `Limiter(enabled=False)`, then try to call any route which is decorated with `limiter.limit()`, we are getting following exception -

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/.venv/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/.venv/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/.venv/lib/python3.7/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/.venv/lib/python3.7/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/.venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/.venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/.venv/lib/python3.7/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/.venv/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/.venv/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/.venv/lib/python3.7/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/.venv/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/.venv/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/.venv/lib/python3.7/site-packages/fastapi/routing.py", line 202, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/.venv/lib/python3.7/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "/.venv/lib/python3.7/site-packages/slowapi/extension.py", line 636, in async_wrapper
    self._inject_headers(response, request.state.view_rate_limit)
  File "/.venv/lib/python3.7/site-packages/starlette/datastructures.py", line 672, in __getattr__
    raise AttributeError(message.format(self.__class__.__name__, key))
AttributeError: 'State' object has no attribute 'view_rate_limit'

```

**Comment by laurentS** [comment]
@kodekracker Thank you for bringing this up, and sorry about the trouble. I've opened a PR that should fix the problem. Can you try it out with your code, and let me know if it works? If so I'll push out a release to make it official :)

**Comment by kodekracker** [comment]
@laurentS Apologies for the late response. I was not so active on github in recent days. Thanks for quick reply and fix. I tested the PR branch locally in our project, the fix is working fine.

It would be great, if you do quick release along with this fix.

**Comment by ccorley** [comment]
@laurentS Just in case anyone else runs into this, some additional config info.  We are using 1.4 with FastAPI and have a single rate limit for the whole application, without annotation on each endpoint and without including Requests in the endpoint params.  Without setting auto_check to false when enabled is false we get the same error mentioned above, except in a different location: 
```
virtualenvs/connect-aAYf_hvc/lib/python3.8/site-packages/slowapi/middleware.py", line 54, in dispatch
    response = limiter._inject_headers(response, request.state.view_rate_limit)
...
AttributeError: 'State' object has no attribute 'view_rate_limit'
```
The config that resolves this is:
```
    limiter = Limiter(
        key_func=get_remote_address,
        auto_check=False,
        enabled=False,
        default_limits=["5/second"]
    )
```
Conversely, to enable rate limiting, we need auto_check=True and enabled=True.
